### ISSUE TITLE
Add decorators for MarcReader to read files as Java 8 Streams

### ISSUE THREAD

**Issue by adjam** [ksclarke/freelib-marc4j#19]
To enable using MarcReader objects as Iterators and streams, it might be handy to have a utility class along the lines of

https://gist.github.com/adjam/25f615af87ea6e5bfdbcead32c7e313d

This would assume building with and for Java 8+.  An alternative would be to retrofit the MarcReader class to implement the Iterator interface, but that's more invasive.

I can generate a pull request from this if you can suggest a package (org.marc4j.util perhaps?)

**Comment by ksclarke** [comment]
I'm fine with making Java 8+ a requirement since 7 is end of life'd already. A PR for this would be welcome. I think org.marc4j might be better since that's where the readers and writers are and I'd see RecordIterator more akin to them than the sort of secondary utils in the util package. Would you include some tests with it too? Thanks!

**Comment by ksclarke** [comment]
Sorry for delay. Published up to Maven Central now.
